/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.java_chat;

import static com.mycompany.java_chat.chat_sever.Soket;
import static com.mycompany.java_chat.chat_sever.Ss;
import static com.mycompany.java_chat.chat_sever.dis;
import static com.mycompany.java_chat.chat_sever.dout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author 임미희
 */
public class chat_client extends javax.swing.JFrame {
        static Socket Soket;
        static DataInputStream dis;
        static DataOutputStream dout;
        private static String Nic_Name="";
        private static boolean Chat_On_off=true;
    /**
     * Creates new form chat_client
     */
    public chat_client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mse_send = new javax.swing.JButton();
        mse_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mse_area = new javax.swing.JTextArea();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mse_send.setText("보내기");
        mse_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mse_sendActionPerformed(evt);
            }
        });

        mse_area.setColumns(20);
        mse_area.setRows(5);
        jScrollPane1.setViewportView(mse_area);

        Name.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mse_field)
                                .addGap(18, 18, 18)
                                .addComponent(mse_send)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mse_field, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mse_send, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mse_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mse_sendActionPerformed
                // TODO add your handling code here:
               if(Chat_On_off){
                    try{
        
                    String msg = mse_field.getText();
                    //msg = mse_field.getText()+"/"+Name.getText();
                    dout.writeUTF(msg);
                    Nic_Name=Name.getText();
                    
                    mse_area.setText(mse_area.getText()+"\n "+Name.getText()+" : "+mse_field.getText());
                    mse_field.setText("");  
                    if(msg.equals("exit")){
                         mse_area.setText(mse_area.getText()+"\n "+Nic_Name+"님이 채팅방을 나갔습니다.");
                         Chat_On_off=false;
                    }
                   }catch(Exception e){

                   }
               }
               
        
    }//GEN-LAST:event_mse_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chat_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chat_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chat_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chat_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chat_client().setVisible(true);
            }
        });
        
        try{
            String Mes="";
            Soket = new Socket("127.0.0.1",2000); // 클라이 언트랑 서버 연결
            dis = new DataInputStream(Soket.getInputStream());
            dout = new DataOutputStream(Soket.getOutputStream());
            
//            while(Chat_On_off){
//                Nic_Name=Name.getText();
//                Mes = dis.readUTF();
//                mse_area.setText(mse_area.getText()+"\n 관리자 : "+Mes);
//                
//            }
            while(!Mes.equals("exit")){
                
                Mes = dis.readUTF();
                mse_area.setText(mse_area.getText()+"\n 관리자 : "+Mes);
                
            }
               
             
            
        }catch(Exception e){
            
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField Name;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea mse_area;
    private javax.swing.JTextField mse_field;
    private javax.swing.JButton mse_send;
    // End of variables declaration//GEN-END:variables
}
